# Generated by Django 5.2.10 on 2026-01-25 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='收藏内容的标题', max_length=500, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', help_text='收藏内容的简要描述', verbose_name='描述')),
                ('url', models.URLField(max_length=2000, verbose_name='原始链接')),
                ('domain', models.CharField(help_text='来源网站域名', max_length=255, verbose_name='域名')),
                ('favicon', models.URLField(blank=True, max_length=500, null=True, verbose_name='网站图标')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图片')),
                ('content', models.TextField(blank=True, default='', help_text='抓取的网页正文内容', verbose_name='正文内容')),
                ('html_content', models.TextField(blank=True, default='', help_text='原始 HTML 内容，用于二次处理', verbose_name='原始HTML')),
                ('is_processed', models.BooleanField(default=False, help_text='标记内容是否已成功抓取和处理', verbose_name='是否已处理')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='collections_owner_i_df5f43_idx'), models.Index(fields=['owner', 'is_processed'], name='collections_owner_i_224f8e_idx')],
            },
        ),
    ]
