# Generated by Django 5.2.10 on 2026-01-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='用户邮箱，唯一标识', max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
