# Generated by Django 5.2.10 on 2026-01-27 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '亮色'), ('dark', '暗色'), ('auto', '跟随系统')], default='light', max_length=20, verbose_name='主题')),
                ('language', models.CharField(default='zh-CN', max_length=10, verbose_name='语言')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('notes_count', models.PositiveIntegerField(default=0, verbose_name='笔记数量')),
                ('categories_count', models.PositiveIntegerField(default=0, verbose_name='分类数量')),
                ('tags_count', models.PositiveIntegerField(default=0, verbose_name='标签数量')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
