# Generated by Django 5.2.10 on 2026-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='用户头像的URL地址（外部链接）', max_length=500, null=True, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
