# Generated by Django 5.2.10 on 2026-01-25 15:22

import apps.attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to=apps.attachments.models.attachment_file_path, verbose_name='文件')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频'), ('audio', '音频'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note', verbose_name='所属笔记')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='attachments_owner_i_b8e723_idx'), models.Index(fields=['note', 'created_at'], name='attachments_note_id_bea9dd_idx')],
            },
        ),
    ]
