# Generated by Django 5.2.10 on 2026-01-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('note', '笔记'), ('category', '分类'), ('tag', '标签'), ('collection', '收藏')], max_length=20, verbose_name='节点类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='显示标签')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '图谱节点',
                'verbose_name_plural': '图谱节点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('related', '相关'), ('parent', '父子'), ('similar', '相似'), ('reference', '引用')], default='related', max_length=20, verbose_name='链接类型')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_links', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='graph.graphnode', verbose_name='源节点')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='graph.graphnode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '图谱链接',
                'verbose_name_plural': '图谱链接',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_link_per_nodes')],
            },
        ),
    ]
