# Generated by Django 5.2.10 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphlink',
            name='link_type',
            field=models.CharField(choices=[('related', '相关'), ('parent', '父子/分类'), ('tagged', '标签'), ('similar', '相似'), ('reference', '引用')], default='related', max_length=20, verbose_name='链接类型'),
        ),
    ]
