# Generated by Django 5.2.10 on 2026-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_alter_graphlink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='锁定节点不会被自动同步覆盖', verbose_name='是否锁定'),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='original_id',
            field=models.IntegerField(blank=True, help_text='同步自其他表时的原始ID', null=True, verbose_name='原始数据ID'),
        ),
        migrations.AddField(
            model_name='graphnode',
            name='source',
            field=models.CharField(choices=[('sync', '自动同步'), ('manual', '手动创建')], default='sync', max_length=20, verbose_name='数据来源'),
        ),
    ]
