# Generated by Django 5.2.10 on 2026-01-25 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL别名')),
                ('content', models.JSONField(default=list, help_text='TipTap JSON 内容', verbose_name='内容')),
                ('plain_text', models.TextField(blank=True, default='', help_text='用于全文搜索', verbose_name='纯文本内容')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='categories.category', verbose_name='分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='notes_note_owner_i_3ca543_idx'), models.Index(fields=['owner', 'is_archived'], name='notes_note_owner_i_80808c_idx'), models.Index(fields=['owner', 'is_pinned'], name='notes_note_owner_i_354ce1_idx')],
            },
        ),
    ]
