# Generated by Django 5.2.10 on 2026-01-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_notes',
            field=models.ManyToManyField(blank=True, to='notes.note', verbose_name='相关笔记'),
        ),
    ]
