# Generated by Django 5.2.10 on 2026-01-25 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL别名')),
                ('color', models.CharField(default='#1890ff', help_text='十六进制颜色值，如 #1890ff', max_length=7, verbose_name='颜色')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='标签描述')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['-usage_count', 'name'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'owner'), name='unique_tag_slug_per_user')],
            },
        ),
    ]
